
import React from 'react';
import { 
  AlertTriangle, 
  CheckCircle, 
  XCircle, 
  ShieldAlert, 
  ShieldCheck, 
  FileSearch, 
  Printer, 
  Scale,
  History,
  Check,
  Lock,
  Trash2,
  Shield,
  FileQuestion,
  HelpCircle
} from 'lucide-react';
import { AnalysisResult } from '../types';

interface AnalysisReportProps {
  report: AnalysisResult;
}

const AnalysisReport: React.FC<AnalysisReportProps> = ({ report }) => {
  
  // Determine color theme based on risk level
  const getRiskColor = (score: number) => {
    if (score < 30) return 'text-emerald-600 bg-emerald-50 border-emerald-200';
    if (score < 60) return 'text-yellow-600 bg-yellow-50 border-yellow-200';
    return 'text-red-600 bg-red-50 border-red-200';
  };

  const riskColorClass = getRiskColor(report.riskScore);

  // Determine Buyer Protection Theme
  const isBuyerSafe = report.buyerProtection.verdict === 'Buyer Safe' || report.buyerProtection.verdict === 'Neutral';
  const protectionTheme = isBuyerSafe 
    ? 'bg-emerald-50 border-emerald-200 text-emerald-900' 
    : 'bg-red-50 border-red-200 text-red-900';
  const protectionBadgeTheme = isBuyerSafe
    ? 'bg-emerald-100 text-emerald-800'
    : 'bg-red-100 text-red-800';

  const handlePrint = () => {
    // Scroll to top before printing
    window.scrollTo(0, 0);
    // Small delay to ensure layout is ready
    setTimeout(() => {
      window.print();
    }, 100);
  };

  return (
    <div className="print-report bg-slate-50 font-sans" style={{ minHeight: '100%' }}>
      
      {/* Header Actions - Hidden when printing */}
      <div className="flex items-center justify-between mb-6 pb-4 border-b border-slate-200 no-print">
        <div>
          <h2 className="text-3xl font-bold text-slate-800 bangla-text">জমি চেক রিপোর্ট</h2>
          <p className="text-sm text-slate-500 mt-1">Generated by JomiCheck AI • Pro Grade Analysis</p>
        </div>
        <button 
             onClick={handlePrint}
             className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-slate-700 bg-white border border-slate-300 hover:bg-slate-50 rounded-lg shadow-sm transition-colors"
           >
             <Printer size={16} />
             <span className="hidden sm:inline">Download PDF</span>
        </button>
      </div>
      
      {/* Print Header - Only visible when printing */}
      <div className="hidden print:block mb-6 pb-4 border-b-2 border-green-600">
        <div className="flex items-center gap-3 mb-2">
          <div className="w-10 h-10 bg-green-600 rounded-lg flex items-center justify-center">
            <Check size={24} className="text-white" />
          </div>
          <div>
            <h2 className="text-2xl font-bold text-slate-900">JomiCheck Report</h2>
            <p className="text-sm text-slate-600">জমি চেক রিপোর্ট</p>
          </div>
        </div>
        <p className="text-xs text-slate-500 mt-2">
          Generated: {new Date().toLocaleDateString('en-BD', { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' })}
          {' '} • www.jomicheck.com
        </p>
      </div>

      <div className="pb-10">
        
        {/* 1. Risk Dashboard */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          
          {/* Risk Gauge Card */}
          <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm flex flex-col items-center justify-center text-center relative overflow-hidden">
             <div className="relative z-10">
               <span className="text-sm font-semibold text-slate-400 uppercase tracking-wider">Risk Score</span>
               <div className={`text-6xl font-extrabold mt-3 mb-2 ${report.riskScore > 50 ? 'text-red-600' : 'text-emerald-600'}`}>
                 {report.riskScore}/100
               </div>
               <div className={`inline-block px-4 py-1.5 rounded-full text-base font-bold border ${riskColorClass}`}>
                 {report.riskLevel}
               </div>
             </div>
             {/* Background decoration */}
             <div className={`absolute bottom-0 left-0 right-0 h-2 ${report.riskScore > 50 ? 'bg-red-500' : 'bg-emerald-500'} opacity-20`}></div>
          </div>

          {/* Document Summary */}
          <div className="md:col-span-2 bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
             <h3 className="text-sm font-semibold text-slate-400 uppercase tracking-wider mb-4 flex items-center gap-2">
               <FileSearch size={16} /> Document Details
             </h3>
             <div className="grid grid-cols-2 gap-4">
                <div className="p-4 bg-slate-50 rounded-lg">
                  <span className="text-xs text-slate-500 block">Type</span>
                  <span className="font-semibold text-lg text-slate-800 bangla-text">{report.documentType}</span>
                </div>
                <div className="p-4 bg-slate-50 rounded-lg">
                  <span className="text-xs text-slate-500 block">Property Amount</span>
                  <span className="font-semibold text-lg text-slate-800 bangla-text">{report.summary.propertyAmount || "N/A"}</span>
                </div>
                <div className="p-4 bg-slate-50 rounded-lg">
                  <span className="text-xs text-slate-500 block">Mouza</span>
                  <span className="font-semibold text-lg text-slate-800 bangla-text">{report.summary.mouza || "N/A"}</span>
                </div>
                <div className="p-4 bg-slate-50 rounded-lg">
                  <span className="text-xs text-slate-500 block">Deed No / Date</span>
                  <span className="font-semibold text-lg text-slate-800 bangla-text">{report.summary.deedNo || "N/A"} • {report.summary.date || "N/A"}</span>
                </div>
             </div>
          </div>
        </div>

        {/* 2. What to Fix (Critical Issues) */}
        {report.criticalIssues.length > 0 && (
          <div className="mb-6 bg-red-50 border border-red-200 rounded-xl overflow-hidden shadow-sm">
            <div className="bg-red-100/50 px-6 py-4 border-b border-red-200 flex items-center gap-3">
              <ShieldAlert className="text-red-600" size={24} />
              <h3 className="text-xl font-bold text-red-800">What to Fix</h3>
            </div>
            <div className="p-6">
              <ul className="space-y-4">
                {report.criticalIssues.map((issue, idx) => (
                  <li key={idx} className="flex items-start gap-3 text-red-900 font-medium text-base bangla-text">
                    <XCircle className="shrink-0 mt-0.5 text-red-500" size={20} />
                    {issue}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        )}

        {/* 3. What is Missing (New Section) */}
        {report.missingInfo && report.missingInfo.length > 0 && (
          <div className="mb-8 bg-blue-50 border border-blue-200 rounded-xl overflow-hidden shadow-sm">
            <div className="bg-blue-100/50 px-6 py-4 border-b border-blue-200 flex items-center gap-3">
              <FileQuestion className="text-blue-600" size={24} />
              <h3 className="text-xl font-bold text-blue-800">What is Missing</h3>
            </div>
            <div className="p-6">
              <ul className="space-y-4">
                {report.missingInfo.map((info, idx) => (
                  <li key={idx} className="flex items-start gap-3 text-blue-900 font-medium text-base bangla-text">
                    <HelpCircle className="shrink-0 mt-0.5 text-blue-500" size={20} />
                    {info}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        )}

        {/* 4. Good vs Bad Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
          {/* What is Good */}
          <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
             <div className="px-6 py-4 border-b border-slate-100 bg-emerald-50/50 flex items-center gap-2">
               <CheckCircle className="text-emerald-600" size={20} />
               <h3 className="font-bold text-lg text-slate-800">What is Good</h3>
             </div>
             <div className="p-6">
               <ul className="space-y-4">
                 {report.goodPoints.map((point, idx) => (
                   <li key={idx} className="flex items-start gap-3 text-slate-700 text-base bangla-text">
                     <div className="bg-emerald-100 text-emerald-600 rounded-full p-0.5 mt-0.5 shrink-0">
                        <Check size={14} strokeWidth={3} />
                     </div>
                     {point}
                   </li>
                 ))}
                 {report.goodPoints.length === 0 && <span className="text-slate-400 text-sm italic">No significant strengths found.</span>}
               </ul>
             </div>
          </div>

          {/* What is Bad */}
          <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
             <div className="px-6 py-4 border-b border-slate-100 bg-orange-50/50 flex items-center gap-2">
               <AlertTriangle className="text-orange-600" size={20} />
               <h3 className="font-bold text-lg text-slate-800">What is Bad</h3>
             </div>
             <div className="p-6">
               <ul className="space-y-4">
                 {report.badPoints.map((point, idx) => (
                   <li key={idx} className="flex items-start gap-3 text-slate-700 text-base bangla-text">
                     <span className="mt-2 w-2 h-2 rounded-full bg-orange-500 shrink-0"></span>
                     {point}
                   </li>
                 ))}
                  {report.badPoints.length === 0 && <span className="text-slate-400 text-sm italic">No minor issues found.</span>}
               </ul>
             </div>
          </div>
        </div>

        {/* 5. Deep Dives: Chain of Title & Buyer Protection */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
          
          {/* Chain of Title */}
          <div className="bg-slate-50 rounded-xl border border-slate-200 p-6 flex flex-col">
            <h3 className="font-bold text-lg text-slate-800 mb-6 flex items-center gap-2">
              <History size={20} className="text-indigo-600"/> 
              Chain of Title (মালিকানা ইতিহাস)
            </h3>
            
            {/* Visual Timeline */}
            <div className="mb-6 relative border-l-2 border-indigo-200 ml-2.5 my-2 space-y-8">
               {report.chainOfTitleTimeline && report.chainOfTitleTimeline.length > 0 ? (
                 report.chainOfTitleTimeline.map((item, idx) => (
                   <div key={idx} className="relative pl-8">
                      <span className="absolute -left-[9px] top-1.5 w-4 h-4 bg-indigo-100 border-2 border-indigo-500 rounded-full"></span>
                      <span className="text-sm font-bold text-indigo-600 block mb-0.5">{item.date}</span>
                      <span className="text-base text-slate-800 bangla-text leading-tight block font-medium">{item.event}</span>
                   </div>
                 ))
               ) : (
                 <div className="pl-6 text-sm text-slate-400 italic">Timeline data not available.</div>
               )}
            </div>

            <div className="mt-auto pt-6 border-t border-slate-200">
              <p className="text-base text-slate-600 leading-relaxed bangla-text text-justify">
                {report.chainOfTitleAnalysis}
              </p>
            </div>
          </div>

          {/* Buyer Fairness Check */}
          <div className={`rounded-xl border p-6 ${protectionTheme}`}>
            <h3 className="font-bold text-lg mb-4 flex items-center gap-2">
              {isBuyerSafe ? (
                 <ShieldCheck size={20} className="text-emerald-600"/>
              ) : (
                 <ShieldAlert size={20} className="text-red-600"/>
              )}
              Buyer Fairness Check
            </h3>
            <div className="mb-4">
              <span className={`px-3 py-1.5 rounded text-sm font-bold uppercase tracking-wide ${protectionBadgeTheme}`}>
                Verdict: {report.buyerProtection.verdict}
              </span>
            </div>
            <p className="text-base leading-relaxed bangla-text">
              {report.buyerProtection.details}
            </p>
          </div>

        </div>

        {/* 6. Suggestions for Improvement */}
        <div className="bg-slate-900 rounded-xl p-6 md:p-8 text-white shadow-lg">
          <h3 className="text-xl font-bold mb-6 flex items-center gap-2">
            <ShieldCheck size={28} className="text-emerald-400" />
            Suggestions for Improvement
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
             {report.nextSteps.map((step, idx) => (
               <div key={idx} className="flex items-start gap-3 bg-white/10 p-4 rounded-lg border border-white/10">
                 <div className="bg-brand-500 rounded-full w-6 h-6 flex items-center justify-center shrink-0 text-sm font-bold text-white">
                   {idx + 1}
                 </div>
                 <span className="text-base text-slate-200 bangla-text">{step}</span>
               </div>
             ))}
          </div>
        </div>

        {/* 7. Trust & Privacy */}
        <div className="mt-8 bg-white rounded-xl border border-slate-200 p-6">
          <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider mb-4 flex items-center gap-2">
            <Shield size={18} className="text-slate-400" />
            Trust & Privacy
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="flex items-center gap-3">
              <div className="p-2.5 bg-slate-50 rounded-full text-slate-500">
                <Lock size={18} />
              </div>
              <span className="text-sm text-slate-600 font-medium">Your documents are encrypted.</span>
            </div>
            <div className="flex items-center gap-3">
              <div className="p-2.5 bg-slate-50 rounded-full text-slate-500">
                <ShieldCheck size={18} />
              </div>
              <span className="text-sm text-slate-600 font-medium">We never sell or share your deeds.</span>
            </div>
            <div className="flex items-center gap-3">
              <div className="p-2.5 bg-slate-50 rounded-full text-slate-500">
                <Trash2 size={18} />
              </div>
              <span className="text-sm text-slate-600 font-medium">You can delete any document from your account at any time.</span>
            </div>
          </div>
        </div>

        {/* Disclaimer */}
        <div className="mt-8 text-center">
          <p className="text-sm text-slate-400 max-w-2xl mx-auto bangla-text leading-relaxed">
            <strong>Disclaimer:</strong> This report is generated by AI based on the documents provided. It does not constitute a final legal opinion. Always verify the physical records at the local AC Land and Registry office before financial transaction.
          </p>
        </div>

      </div>
    </div>
  );
};

export default AnalysisReport;
